### Ajouter utilisateur ADMIN
POST http://localhost:8080/api/utilisateurs/ajouterUtilisateur
Content-Type: application/json

{
  "nom": "El Issaoui",
  "prenom": "Hassan",
  "login": "hassan",
  "motDePasse": "1234",
  "email": "hassan@gmail.com",
  "actif": true,
  "role": {
    "id": 1
  }
}

### Ajouter utilisateur GESTIONNAIRE_STOCK
POST http://localhost:8080/api/utilisateurs/ajouterUtilisateur
Content-Type: application/json

{
  "nom": "Gestionnaire",
  "prenom": "Stock",
  "login": "gestionnaire",
  "motDePasse": "1234",
  "email": "gestionnaire@gmail.com",
  "actif": true,
  "role": {
    "id": 2
  }
}

### Afficher les utilisateurs
GET http://localhost:8080/api/utilisateurs/afficherUtilisateurs